// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="sst-env.d.ts" />

import "sst";

/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */

/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    fortuna: {
      type: "sst.aws.Nextjs";
      url: string;
    };
  }
}

export {};
