import "~/styles/globals.css";

import type { Metadata } from "next";
import SideNav from "~/components/nav/SideNav";
import { ThemeProvider } from "~/components/theme/theme-provider";
import ThemeToggle from "~/components/theme/ThemeToggle";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <TRPCReactProvider>
          <ThemeProvider
            attribute={"class"}
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="relative flex h-screen overflow-hidden">
              <SideNav />
              <main className="flex-1">{children}</main>
            </div>
            <ThemeToggle />
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
